# Generated by Django 3.2 on 2021-04-10 19:57

from django.db import migrations
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
