# Generated by Django 3.2 on 2021-04-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210416_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersplittext',
            name='section',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.DeleteModel(
            name='VideoSection',
        ),
        migrations.DeleteModel(
            name='HeaderSection',
        ),
        migrations.DeleteModel(
            name='HeaderSplitText',
        ),
    ]
