# Generated by Django 3.2 on 2021-04-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('alt', models.CharField(max_length=100, verbose_name='Alt')),
                ('detail', models.TextField(verbose_name='Detail')),
                ('name', models.CharField(max_length=100, verbose_name='Fullname')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('age', models.IntegerField(max_length=2, verbose_name='Age')),
                ('email', models.EmailField(max_length=120, verbose_name='email')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
